# Generated by Django 2.1.7 on 2019-07-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimepositionhash',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_hash_positions', to='account.RealTimeIndividual'),
        ),
    ]
