# Generated by Django 2.1.7 on 2019-07-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_realtimepositionhash_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimepositionhash',
            name='datetime_recorded',
            field=models.DateTimeField(null=True),
        ),
    ]
