# Generated by Django 2.1.7 on 2019-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190323_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='Africa/Kigali', max_length=50),
        ),
    ]
