# Generated by Django 2.1.7 on 2019-04-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_organization_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
