# Generated by Django 2.1.7 on 2019-07-07 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_realtimepositionhash_datetime_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimepositionhash',
            name='datetime_recorded',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 12, 13)),
            preserve_default=False,
        ),
    ]
