# Generated by Django 2.1.7 on 2019-07-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190707_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeaccount',
            name='outputs',
            field=models.TextField(null=True),
        ),
    ]
