# Generated by Django 2.1.7 on 2019-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_organization_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(default=None, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
