# Generated by Django 2.1.7 on 2019-07-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_realtimeaccount_outputs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='uid',
            new_name='uid_cognito',
        ),
        migrations.AddField(
            model_name='account',
            name='custom_access_jwt_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='custom_refresh_jwt_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='registration_method',
            field=models.CharField(choices=[('email', 'email'), ('google', 'google')], default='email', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='uid_google',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
