# Generated by Django 2.1.7 on 2019-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190720_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='update_required',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
