# Generated by Django 2.1.7 on 2019-04-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190419_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_object_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
