# Generated by Django 2.1.7 on 2019-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190720_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo_object_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
