# Generated by Django 2.1.7 on 2019-07-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190720_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='google_oauth_access_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='google_oauth_refresh_token',
            field=models.TextField(null=True),
        ),
    ]
