# Generated by Django 2.1.7 on 2019-06-21 12:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_organization_logo_object_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('healthy', 'healthy'), ('unhealthy', 'unhealthy'), ('pending', 'pending')], default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('distance_km_day', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('distance_km_week', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('distance_km_month', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('last_position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
    ]
