# Generated by Django 2.1.7 on 2019-06-21 13:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_realtimeaccount_realtimeindividual'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('datetime_recorded', models.DateTimeField(null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('temp_celcius', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.RealTimeAccount')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.RealTimeIndividual')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='realtimeposition',
            unique_together={('individual', 'position', 'datetime_recorded')},
        ),
    ]
