# Generated by Django 2.1.7 on 2019-08-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190720_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='agol_oauth_access_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='agol_oauth_refresh_token',
            field=models.TextField(null=True),
        ),
    ]
