# Generated by Django 2.1.7 on 2019-08-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190807_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='agol_group_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
