# Generated by Django 2.1.7 on 2019-06-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190621_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeindividual',
            name='datetime_last_position',
            field=models.DateTimeField(null=True),
        ),
    ]
