# Generated by Django 2.1.7 on 2019-06-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_realtimeindividual_datetime_last_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeindividual',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='account_realtimeindividual_related', to='account.RealTimeAccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtimeposition',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_realtimeposition_related', to='account.RealTimeAccount'),
        ),
        migrations.AlterField(
            model_name='realtimeposition',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_realtimeposition_related', to='account.RealTimeIndividual'),
        ),
    ]
