# Generated by Django 2.1.7 on 2019-08-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_organization_agol_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeaccount',
            name='agol_item_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
