# Generated by Django 2.1.7 on 2019-08-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_realtimeaccount_agol_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtimeaccount',
            name='agol_item_id',
        ),
        migrations.AddField(
            model_name='organization',
            name='agol_feature_service_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realtimeaccount',
            name='agol_layer_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
