# Generated by Django 2.1.7 on 2019-06-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190621_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeindividual',
            name='device_id',
            field=models.CharField(default='KC239', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtimeindividual',
            name='monthly_paths',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='realtimeindividual',
            unique_together={('account', 'device_id')},
        ),
    ]
