# Generated by Django 2.1.7 on 2019-08-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190808_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='agol_username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
