# Generated by Django 2.1.7 on 2019-08-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_organization_agol_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='agol_feature_service_id',
        ),
        migrations.AddField(
            model_name='organization',
            name='agol_feature_service_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
