# Generated by Django 2.1.7 on 2019-07-01 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20190622_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimePositionHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash', models.CharField(max_length=255, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.RealTimeAccount')),
            ],
        ),
    ]
