# Generated by Django 2.1.7 on 2019-07-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_realtimepositionhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimepositionhash',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hash_positions', to='account.RealTimeAccount'),
        ),
    ]
