# Generated by Django 2.1.7 on 2019-08-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20190808_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtimeindividual',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterField(
            model_name='realtimeaccount',
            name='provider',
            field=models.CharField(choices=[('orbcomm', 'orbcomm'), ('savannah_tracking', 'savannah_tracking'), ('trbonet', 'trbonet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='realtimeaccount',
            name='source',
            field=models.CharField(choices=[('collar', 'collar'), ('radio', 'radio')], max_length=50),
        ),
    ]
