# Generated by Django 2.1.7 on 2019-07-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20190701_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtimeindividual',
            name='distance_km_day',
        ),
        migrations.RemoveField(
            model_name='realtimeindividual',
            name='distance_km_month',
        ),
        migrations.RemoveField(
            model_name='realtimeindividual',
            name='distance_km_week',
        ),
    ]
