# Generated by Django 2.1.7 on 2019-08-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20190820_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeaccount',
            name='is_synced',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realtimeindividual',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('AB+', 'AB+')], max_length=100, null=True),
        ),
    ]
