# Generated by Django 2.1.7 on 2019-07-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20190701_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeaccount',
            name='device_indexes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realtimeaccount',
            name='organization',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='rt_accounts', to='account.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtimeaccount',
            name='provider',
            field=models.CharField(choices=[('orbcomm', 'orbcomm'), ('savannah_tracking', 'savannah_tracking')], default='orbcomm', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtimeaccount',
            name='source',
            field=models.CharField(choices=[('collar', 'collar')], default='collar', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtimeaccount',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realtimeaccount',
            name='type',
            field=models.CharField(default='elephant', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtimeindividual',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('', '')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realtimeindividual',
            name='call_sign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realtimeindividual',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realtimeindividual',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realtimeindividual',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('broken', 'broken'), ('inactive', 'inactive')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='realtimeindividual',
            name='subtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='realtimeindividual',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rt_individuals', to='account.RealTimeAccount'),
        ),
        migrations.AlterField(
            model_name='realtimeindividual',
            name='monthly_paths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtimeposition',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rt_positions', to='account.RealTimeAccount'),
        ),
        migrations.AlterField(
            model_name='realtimeposition',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rt_positions', to='account.RealTimeIndividual'),
        ),
        migrations.AlterField(
            model_name='realtimepositionhash',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rt_hash_positions', to='account.RealTimeAccount'),
        ),
    ]
