# Generated by Django 2.1.7 on 2019-08-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20190821_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='google_oauth_access_token_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
