# Generated by Django 2.1.7 on 2019-07-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20190703_0707'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='realtimeaccount',
            unique_together={('organization', 'source', 'provider', 'type')},
        ),
    ]
