# Generated by Django 2.1.7 on 2019-08-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_organization_google_oauth_access_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='google_oauth_access_token',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='google_oauth_access_token_expiry',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='google_oauth_refresh_token',
        ),
        migrations.AddField(
            model_name='account',
            name='temp_google_oauth_access_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='temp_google_oauth_access_token_expiry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='temp_google_oauth_refresh_token',
            field=models.TextField(null=True),
        ),
    ]
