# Generated by Django 2.1.7 on 2019-08-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20190828_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeindividual',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
