# Generated by Django 2.1.7 on 2019-09-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_realtimeindividual_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='agol_oauth_access_token_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
