# Generated by Django 2.1.7 on 2019-09-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_organization_agol_oauth_access_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
