# Generated by Django 2.1.7 on 2019-09-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_organization_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
