# Generated by Django 2.1.7 on 2019-09-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_organization_subscription_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='subscription_status',
            new_name='stripe_subscription_status',
        ),
    ]
