# Generated by Django 2.1.7 on 2019-09-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_organization_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
