# Generated by Django 2.1.7 on 2019-09-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_organization_stripe_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='stripe_subscription_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
