# Generated by Django 2.1.7 on 2019-09-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20190919_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_trialing',
            field=models.BooleanField(default=False),
        ),
    ]
