# Generated by Django 2.1.7 on 2019-09-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_organization_is_trialing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_trialing',
            field=models.BooleanField(default=True),
        ),
    ]
