# Generated by Django 2.1.7 on 2019-09-24 19:15

import caracal.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20190924_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimeaccount',
            name='datetime_created',
            field=models.DateTimeField(default=caracal.common.models.get_utc_datetime_now),
        ),
        migrations.AlterField(
            model_name='realtimeindividual',
            name='datetime_created',
            field=models.DateTimeField(default=caracal.common.models.get_utc_datetime_now),
        ),
        migrations.AlterField(
            model_name='realtimeposition',
            name='datetime_created',
            field=models.DateTimeField(default=caracal.common.models.get_utc_datetime_now),
        ),
        migrations.AlterField(
            model_name='realtimepositionhash',
            name='datetime_created',
            field=models.DateTimeField(default=caracal.common.models.get_utc_datetime_now),
        ),
    ]
