# Generated by Django 2.1.7 on 2019-09-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20190924_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_records_limit',
            field=models.IntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='organization',
            name='destinations_limit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='organization',
            name='source_limit',
            field=models.IntegerField(default=10),
        ),
    ]
