# Generated by Django 2.1.7 on 2019-09-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20190925_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtimeposition',
            old_name='temp_celcius',
            new_name='temp_c',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_demo',
        ),
    ]
