# Generated by Django 2.1.7 on 2019-09-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20190927_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='agol_feature_service_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='agol_group_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='agol_oauth_access_token',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='agol_oauth_access_token_expiry',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='agol_oauth_refresh_token',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='agol_username',
        ),
    ]
