# Generated by Django 2.1.7 on 2019-09-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20190927_1801'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='realtimeaccount',
            unique_together=set(),
        ),
    ]
