# Generated by Django 2.1.7 on 2019-09-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20190928_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeaccount',
            name='cloudwatch_rule_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
