# Generated by Django 2.1.7 on 2019-09-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_realtimeaccount_cloudwatch_rule_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtimeaccount',
            old_name='cloudwatch_rule_name',
            new_name='cloudwatch_get_data_rule_name',
        ),
    ]
