# Generated by Django 2.1.7 on 2019-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_auto_20190930_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeaccount',
            name='cloudwatch_update_kml_rule_names',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
