# Generated by Django 2.1.7 on 2019-10-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_realtimeaccount_cloudwatch_update_kml_rule_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtimeaccount',
            name='agol_layer_id',
        ),
    ]
