# Generated by Django 2.1.7 on 2019-11-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_remove_realtimeaccount_agol_layer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtimeindividual',
            name='datetime_last_position',
        ),
        migrations.RemoveField(
            model_name='realtimeindividual',
            name='last_position',
        ),
        migrations.RemoveField(
            model_name='realtimeindividual',
            name='monthly_paths',
        ),
    ]
