# Generated by Django 2.1.7 on 2020-01-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_alertrecipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertrecipient',
            options={'ordering': ['datetime_created']},
        ),
        migrations.AddField(
            model_name='account',
            name='is_jackal_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
