# Generated by Django 2.1.7 on 2019-10-16 13:01

import caracal.common.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0040_remove_realtimeaccount_agol_layer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_recorded', models.DateTimeField()),
                ('is_sent', models.BooleanField()),
                ('other_phone_number', models.CharField(max_length=50)),
                ('duration_secs', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_recorded', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_recorded', models.DateTimeField()),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('accuracy_m', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('write_key', models.CharField(max_length=100)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jackal_network', to='account.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('deployed', 'deployed'), ('inactive', 'inactive'), ('pending', 'pending')], default='pending', max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('mark', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_numbers', models.CharField(blank=True, max_length=255, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='jackal.Network')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_recorded', models.DateTimeField()),
                ('is_sent', models.BooleanField()),
                ('other_phone_number', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='jackal.Network')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='jackal.Phone')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='jackal.Network'),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='jackal.Phone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='jackal.Network'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='jackal.Phone'),
        ),
        migrations.AddField(
            model_name='call',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='jackal.Network'),
        ),
        migrations.AddField(
            model_name='call',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='jackal.Phone'),
        ),
        migrations.AlterUniqueTogether(
            name='text',
            unique_together={('phone', 'datetime_recorded', 'message')},
        ),
    ]
