# Generated by Django 2.1.7 on 2019-10-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='call',
            unique_together={('phone', 'datetime_recorded', 'is_sent', 'other_phone_number', 'duration_secs')},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('phone', 'name', 'phone_number')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('phone', 'datetime_recorded', 'position', 'accuracy_m')},
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together={('network', 'device_id')},
        ),
        migrations.AlterUniqueTogether(
            name='text',
            unique_together={('phone', 'datetime_recorded', 'is_sent', 'other_phone_number', 'message')},
        ),
    ]
