# Generated by Django 2.1.7 on 2019-10-24 09:09

import caracal.common.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0002_auto_20191016_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('mark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterField(
            model_name='network',
            name='write_key',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='call',
            name='other_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='jackal.OtherPhone'),
        ),
        migrations.AlterUniqueTogether(
            name='call',
            unique_together={('phone', 'other_phone', 'datetime_recorded', 'is_sent', 'duration_secs')},
        ),
        migrations.RemoveField(
            model_name='call',
            name='other_phone_number',
        )
    ]
