# Generated by Django 2.1.7 on 2019-10-24 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0003_auto_20191024_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherphone',
            options={'ordering': ['name', 'phone_number']},
        ),
        migrations.AddField(
            model_name='contact',
            name='other_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='jackal.OtherPhone'),
        ),
        migrations.AddField(
            model_name='otherphone',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_phones', to='jackal.Network'),
        ),
        migrations.AddField(
            model_name='text',
            name='other_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='jackal.OtherPhone'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('phone', 'other_phone')},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.AlterUniqueTogether(
            name='otherphone',
            unique_together={('network', 'phone_number')},
        ),
        migrations.AlterUniqueTogether(
            name='text',
            unique_together={('phone', 'other_phone', 'datetime_recorded', 'is_sent', 'message')},
        ),
        migrations.RemoveField(
            model_name='text',
            name='other_phone_number',
        )
    ]
