# Generated by Django 2.1.7 on 2019-10-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0004_auto_20191024_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='other_phone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='jackal.OtherPhone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='other_phone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='jackal.OtherPhone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otherphone',
            name='network',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='other_phones', to='jackal.Network'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text',
            name='other_phone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='jackal.OtherPhone'),
            preserve_default=False,
        ),
    ]
