# Generated by Django 2.1.7 on 2020-02-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0005_auto_20191024_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-datetime_recorded']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-datetime_recorded']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-datetime_recorded']},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['-datetime_recorded']},
        ),
    ]
