# Generated by Django 2.1.7 on 2020-02-14 11:41

import caracal.common.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0006_auto_20200213_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_recorded', models.DateTimeField()),
                ('call_log_id', models.IntegerField()),
                ('duration_secs', models.IntegerField()),
                ('from_me', models.BooleanField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_calls', to='jackal.Network')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_calls', to='jackal.Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_recorded', models.DateTimeField()),
                ('jid_id', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_groups', to='jackal.Network')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_groups', to='jackal.Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_recorded', models.DateTimeField()),
                ('from_me', models.BooleanField()),
                ('media_url', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('messages_id', models.IntegerField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='jackal.Network')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='jackal.Phone')),
                ('whatsapp_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='jackal.WhatsAppGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_recorded', models.DateTimeField()),
                ('jid_id', models.IntegerField()),
                ('phone_number', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(to='jackal.WhatsAppGroup')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_users', to='jackal.Network')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_users', to='jackal.Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='whatsapp_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='jackal.WhatsAppUser'),
        ),
        migrations.AddField(
            model_name='whatsappcall',
            name='whatsapp_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_calls', to='jackal.WhatsAppUser'),
        ),
    ]
