# Generated by Django 2.1.7 on 2020-02-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0007_auto_20200214_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappgroup',
            name='datetime_recorded',
        ),
        migrations.RemoveField(
            model_name='whatsappuser',
            name='datetime_recorded',
        ),
    ]
