# Generated by Django 2.1.7 on 2020-02-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0008_auto_20200214_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcall',
            name='call_log_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappgroup',
            name='jid_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='messages_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappuser',
            name='jid_id',
            field=models.IntegerField(unique=True),
        ),
    ]
