# Generated by Django 2.1.7 on 2020-02-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0009_auto_20200214_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappcall',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterModelOptions(
            name='whatsappgroup',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='user_string',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='user_string',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whatsappcall',
            name='call_log_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='whatsappgroup',
            name='jid_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='whatsappuser',
            name='jid_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappcall',
            unique_together={('datetime_recorded', 'whatsapp_user', 'call_log_id', 'duration_secs')},
        ),
        migrations.AlterUniqueTogether(
            name='whatsappgroup',
            unique_together={('phone', 'user_string')},
        ),
        migrations.RemoveField(
            model_name='whatsappuser',
            name='phone_number',
        ),
        migrations.AlterUniqueTogether(
            name='whatsappuser',
            unique_together={('phone', 'user_string')},
        ),
    ]
