# Generated by Django 2.1.7 on 2020-02-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0010_auto_20200214_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='messages_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappmessage',
            unique_together={('phone', 'datetime_recorded', 'message', 'from_me')},
        ),
    ]
