# Generated by Django 2.1.7 on 2020-02-16 09:47

import caracal.common.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0011_auto_20200214_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_recorded', models.DateTimeField()),
                ('level', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jackal.Network')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jackal.Phone')),
            ],
            options={
                'ordering': ['-datetime_recorded'],
            },
        ),
    ]
