# Generated by Django 2.1.7 on 2020-02-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0012_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherphone',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
