# Generated by Django 2.1.7 on 2020-02-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0013_auto_20200217_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='cloudwatch_update_kml_rule_names',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
