# Generated by Django 2.1.7 on 2020-02-18 11:58

import caracal.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0014_network_cloudwatch_update_kml_rule_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='datetime_last_update',
            field=models.DateTimeField(default=caracal.common.models.get_datetime_epoch_start),
        ),
    ]
