# Generated by Django 2.1.7 on 2020-02-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0015_phone_datetime_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='cloudwatch_update_excel_rule_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappcall',
            unique_together={('datetime_recorded', 'whatsapp_user', 'call_log_id', 'duration_secs', 'from_me')},
        ),
    ]
