# Generated by Django 2.1.7 on 2021-04-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0016_auto_20200225_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherphone',
            name='aliases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
