# Generated by Django 2.1.7 on 2019-07-22 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0009_auto_20190720_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFileAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('healthy', 'healthy'), ('unhealthy', 'unhealthy'), ('pending', 'pending')], default='pending', max_length=50)),
                ('outputs', models.TextField(null=True)),
                ('provider', models.CharField(choices=[('google', 'google')], max_length=100)),
                ('file_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('sheet_ids', models.CharField(default='*', max_length=250)),
                ('header_row_index', models.IntegerField(default=0)),
                ('coordinate_system', models.CharField(choices=[('decimal degrees', 'decimal degrees'), ('degrees minutes seconds', 'degrees minutes seconds'), ('mgrs', 'mgrs')], default='decimal degrees', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_files', to='account.Organization')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='drivefileaccount',
            unique_together={('organization', 'file_id')},
        ),
    ]
