# Generated by Django 2.1.7 on 2019-07-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefileaccount',
            name='file_type',
            field=models.CharField(choices=[('google_sheet', 'google_sheet'), ('excel', 'excel'), ('csv', 'csv'), ('geojson', 'geojson')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
