# Generated by Django 2.1.7 on 2019-07-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_drivefileaccount_file_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drivefileaccount',
            unique_together=set(),
        ),
    ]
