# Generated by Django 2.1.7 on 2019-07-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0003_auto_20190722_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefileaccount',
            name='grid_zone_column_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drivefileaccount',
            name='x_column_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drivefileaccount',
            name='y_column_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drivefileaccount',
            name='coordinate_system',
            field=models.CharField(choices=[('decimal degrees', 'decimal degrees'), ('degrees minutes seconds', 'degrees minutes seconds'), ('utm', 'utm')], default='decimal degrees', max_length=50),
        ),
        migrations.AlterField(
            model_name='drivefileaccount',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
