# Generated by Django 2.1.7 on 2019-07-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0004_auto_20190725_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefileaccount',
            name='date_index',
            field=models.IntegerField(null=True),
        ),
    ]
