# Generated by Django 2.1.7 on 2019-07-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0005_drivefileaccount_date_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivefileaccount',
            old_name='date_index',
            new_name='date_column_index',
        ),
    ]
