# Generated by Django 2.1.7 on 2019-08-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0006_auto_20190729_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefileaccount',
            name='output_notes',
            field=models.BooleanField(default=False),
        ),
    ]
