# Generated by Django 2.1.7 on 2019-08-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0007_drivefileaccount_output_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivefileaccount',
            name='coordinate_system',
            field=models.CharField(choices=[('dd', 'dd'), ('dms', 'dms'), ('utm', 'utm')], default='decimal degrees', max_length=50),
        ),
    ]
