# Generated by Django 2.1.7 on 2019-08-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0008_auto_20190807_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefileaccount',
            name='google_oauth_access_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='drivefileaccount',
            name='google_oauth_access_token_expiry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='drivefileaccount',
            name='google_oauth_refresh_token',
            field=models.TextField(null=True),
        ),
    ]
