# Generated by Django 2.1.7 on 2019-09-24 19:15

import caracal.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0009_auto_20190828_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivefileaccount',
            name='datetime_created',
            field=models.DateTimeField(default=caracal.common.models.get_utc_datetime_now),
        ),
    ]
