# Generated by Django 2.1.7 on 2019-09-27 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drives', '0010_auto_20190924_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivefileaccount',
            name='output_notes',
        ),
        migrations.AddField(
            model_name='drivefileaccount',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
