# Generated by Django 2.1.7 on 2019-09-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0011_auto_20190927_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivefileaccount',
            name='x_column_index',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drivefileaccount',
            name='y_column_index',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
