# Generated by Django 2.1.7 on 2019-10-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0012_auto_20190928_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefileaccount',
            name='most_recent_s3_object_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
