# Generated by Django 2.1.7 on 2019-10-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0013_drivefileaccount_most_recent_s3_object_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefileaccount',
            name='cloudwatch_get_data_rule_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drivefileaccount',
            name='cloudwatch_update_kml_rule_names',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='drivefileaccount',
            name='file_type',
            field=models.CharField(choices=[('google_sheet', 'google_sheet')], max_length=50),
        ),
    ]
