# Generated by Django 2.1.7 on 2019-03-23 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190323_1704'),
        ('collars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaraccount',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Organization'),
            preserve_default=False,
        ),
    ]
