# Generated by Django 2.1.7 on 2019-03-23 21:21

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0002_collaraccount_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollarProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('base_url', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='collaraccount',
            old_name='provider_name',
            new_name='provider_short_name',
        ),
    ]
