# Generated by Django 2.1.7 on 2019-03-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190323_1704'),
        ('collars', '0003_auto_20190323_2121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaraccount',
            unique_together={('organization', 'provider_short_name', 'species', 'timezone', 'company_id', 'username', 'password')},
        ),
    ]
