# Generated by Django 2.1.7 on 2019-03-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0004_auto_20190323_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollarId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collar_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='collarindividual',
            name='account',
        ),
        migrations.RemoveField(
            model_name='collarindividual',
            name='collar_id',
        ),
        migrations.RemoveField(
            model_name='collarindividual',
            name='type',
        ),
        migrations.AddField(
            model_name='collaraccount',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collar_accounts', to='collars.CollarProvider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collarindividual',
            name='subtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collarindividual',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collarindividual',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collarindividual',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('broken', 'broken'), ('dead', 'dead'), ('unknown', 'unknown')], max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='collaraccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='collarid',
            name='collar_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collar_records', to='collars.CollarAccount'),
        ),
        migrations.AddField(
            model_name='collarid',
            name='collar_individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collar_records', to='collars.CollarIndividual'),
        ),
        migrations.RemoveField(
            model_name='collaraccount',
            name='provider_short_name',
        ),
        migrations.AddField(
            model_name='collaraccount',
            name='individuals',
            field=models.ManyToManyField(through='collars.CollarId', to='collars.CollarIndividual'),
        ),
    ]
