# Generated by Django 2.1.7 on 2019-03-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0005_auto_20190324_1025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collarprovider',
            unique_together={('name', 'short_name', 'base_url')},
        ),
    ]
