# Generated by Django 2.1.7 on 2019-03-24 14:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0006_auto_20190324_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='collarid',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='collarid',
            name='datetime_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='collarid',
            name='datetime_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='collarid',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collarid',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='collarid',
            unique_together={('collar_id', 'collar_account', 'collar_individual')},
        ),
    ]
