# Generated by Django 2.1.7 on 2019-03-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0007_auto_20190324_1451'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collarid',
            unique_together={('collar_id', 'collar_account')},
        ),
    ]
