# Generated by Django 2.1.7 on 2019-03-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0008_auto_20190324_1453'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collarid',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='collarid',
            name='collar_account',
        ),
        migrations.RemoveField(
            model_name='collarid',
            name='collar_individual',
        ),
        migrations.RemoveField(
            model_name='collaraccount',
            name='individuals',
        ),
        migrations.AddField(
            model_name='collarindividual',
            name='collar_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collar_individuals', to='collars.CollarAccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collarindividual',
            name='collar_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='collarindividual',
            unique_together={('collar_account', 'collar_id')},
        ),
        migrations.DeleteModel(
            name='CollarId',
        ),
    ]
