# Generated by Django 2.1.7 on 2019-03-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0009_auto_20190324_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collarindividual',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collarindividual',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('broken', 'broken'), ('dead', 'dead'), ('unknown', 'unknown')], max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='collarposition',
            unique_together={('datetime_recorded', 'individual', 'position')},
        ),
    ]
