# Generated by Django 2.1.7 on 2019-04-01 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collars', '0010_auto_20190324_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollarAccountActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('add', 'add'), ('update_individual', 'update_individual'), ('update_account', 'update_account'), ('delete', 'delete')], max_length=100)),
                ('collar_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collar_account_activities', to='collars.CollarAccount')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collar_account_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
