# Generated by Django 2.1.7 on 2019-04-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0011_collaraccountactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaraccount',
            old_name='company_id',
            new_name='orbcomm_company_id',
        ),
        migrations.RenameField(
            model_name='collaraccount',
            old_name='timezone',
            new_name='orbcomm_timezone',
        ),
        migrations.RenameField(
            model_name='collaraccount',
            old_name='password',
            new_name='savannah_password',
        ),
        migrations.RenameField(
            model_name='collaraccount',
            old_name='username',
            new_name='savannah_username',
        ),
    ]
