# Generated by Django 2.1.7 on 2019-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0012_auto_20190407_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='collarposition',
            name='savannah_tracking_id',
            field=models.IntegerField(null=True),
        ),
    ]
