# Generated by Django 2.1.7 on 2019-04-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0013_collarposition_savannah_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collarposition',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
