# Generated by Django 2.1.7 on 2019-04-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0014_collarposition_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collarposition',
            name='savannah_tracking_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
