# Generated by Django 2.1.7 on 2019-04-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0015_auto_20190407_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='collarposition',
            name='collar_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='collars.CollarAccount'),
        ),
        migrations.AlterField(
            model_name='collarposition',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='collars.CollarIndividual'),
        ),
    ]
