# Generated by Django 2.1.7 on 2019-04-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0016_auto_20190416_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collarindividual',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('broken', 'broken'), ('dead', 'dead'), ('unknown', 'unknown')], default='active', max_length=100, null=True),
        ),
    ]
