# Generated by Django 2.1.7 on 2019-04-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0017_auto_20190416_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaraccount',
            old_name='savannah_password',
            new_name='savannah_tracking_password',
        ),
        migrations.RenameField(
            model_name='collaraccount',
            old_name='savannah_username',
            new_name='savannah_tracking_username',
        ),
    ]
