# Generated by Django 2.1.7 on 2019-04-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0018_auto_20190419_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaraccount',
            options={'ordering': ['provider__name', '-datetime_created']},
        ),
        migrations.AlterModelOptions(
            name='collarindividual',
            options={'ordering': ['status', 'name']},
        ),
        migrations.AlterField(
            model_name='collarposition',
            name='collar_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='collars.CollarAccount'),
            preserve_default=False,
        ),
    ]
