# Generated by Django 2.1.7 on 2019-04-20 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0019_auto_20190419_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaraccountactivity',
            name='collar_account',
        ),
        migrations.RemoveField(
            model_name='collaraccountactivity',
            name='user_account',
        ),
        migrations.AlterModelOptions(
            name='collarposition',
            options={'ordering': ['datetime_recorded']},
        ),
        migrations.AlterField(
            model_name='collaraccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collar_accounts', to='account.Organization'),
        ),
        migrations.DeleteModel(
            name='CollarAccountActivity',
        ),
    ]
