# Generated by Django 2.1.7 on 2019-05-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0020_auto_20190420_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaraccount',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
