# Generated by Django 2.1.7 on 2019-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0021_collaraccount_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collarposition',
            name='savannah_tracking_id',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterUniqueTogether(
            name='collarposition',
            unique_together={('datetime_recorded', 'individual', 'position', 'savannah_tracking_id')},
        ),
    ]
