# Generated by Django 2.1.7 on 2019-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0022_auto_20190526_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaraccount',
            name='status',
            field=models.CharField(choices=[('healthy', 'healthy'), ('unhealthy', 'unhealthy'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
