# Generated by Django 2.1.7 on 2019-06-21 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_realtimeaccount_realtimeindividual'),
        ('collars', '0023_collaraccount_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaraccount',
            name='datetime_created',
        ),
        migrations.RemoveField(
            model_name='collaraccount',
            name='datetime_deleted',
        ),
        migrations.RemoveField(
            model_name='collaraccount',
            name='datetime_updated',
        ),
        migrations.RemoveField(
            model_name='collaraccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='collaraccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='collaraccount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='collaraccount',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='collarindividual',
            name='datetime_created',
        ),
        migrations.RemoveField(
            model_name='collarindividual',
            name='datetime_deleted',
        ),
        migrations.RemoveField(
            model_name='collarindividual',
            name='datetime_updated',
        ),
        migrations.RemoveField(
            model_name='collarindividual',
            name='id',
        ),
        migrations.RemoveField(
            model_name='collarindividual',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='collarindividual',
            name='uid',
        ),
        migrations.AddField(
            model_name='collaraccount',
            name='realtimeaccount_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.RealTimeAccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collarindividual',
            name='realtimeindividual_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.RealTimeIndividual'),
            preserve_default=False,
        ),
    ]
