# Generated by Django 2.1.7 on 2019-06-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190621_1312'),
        ('collars', '0024_auto_20190621_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbcommCollarPosition',
            fields=[
                ('realtimeposition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.RealTimePosition')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.realtimeposition',),
        ),
        migrations.CreateModel(
            name='SavannahTrackingCollarPosition',
            fields=[
                ('realtimeposition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.RealTimePosition')),
                ('savannah_tracking_id', models.BigIntegerField(default=-1)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.realtimeposition',),
        ),
        migrations.AlterModelOptions(
            name='collarposition',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='collarposition',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='collarposition',
            name='datetime_created',
        ),
        migrations.RemoveField(
            model_name='collarposition',
            name='datetime_recorded',
        ),
        migrations.RemoveField(
            model_name='collarposition',
            name='position',
        ),
        migrations.RemoveField(
            model_name='collarposition',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='collarposition',
            name='uid',
        ),
    ]
