# Generated by Django 2.1.7 on 2019-06-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0025_auto_20190621_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collarposition',
            name='collar_account',
        ),
        migrations.RemoveField(
            model_name='collarposition',
            name='individual',
        ),
        migrations.DeleteModel(
            name='CollarPosition',
        ),
    ]
