# Generated by Django 2.1.7 on 2019-06-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190621_1338'),
        ('collars', '0026_auto_20190621_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaraccount',
            name='realtimeaccount_ptr',
        ),
        migrations.AddField(
            model_name='collaraccount',
            name='account_ptr',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='collar_account', serialize=False, to='account.RealTimeAccount'),
            preserve_default=False,
        ),
    ]
