# Generated by Django 2.1.7 on 2019-06-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190621_1338'),
        ('collars', '0027_auto_20190621_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collarindividual',
            name='realtimeindividual_ptr',
        ),
        migrations.RemoveField(
            model_name='orbcommcollarposition',
            name='realtimeposition_ptr',
        ),
        migrations.RemoveField(
            model_name='savannahtrackingcollarposition',
            name='realtimeposition_ptr',
        ),
        migrations.AddField(
            model_name='collarindividual',
            name='individual_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='collar_individual', serialize=False, to='account.RealTimeIndividual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orbcommcollarposition',
            name='position_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='orbcomm_collar_position', serialize=False, to='account.RealTimePosition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savannahtrackingcollarposition',
            name='position_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='savannah_tracking_collar_position', serialize=False, to='account.RealTimePosition'),
            preserve_default=False,
        ),
    ]
