# Generated by Django 2.1.7 on 2019-06-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0028_auto_20190621_1348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collarindividual',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='collarindividual',
            name='collar_id',
        ),
    ]
