# Generated by Django 2.1.7 on 2019-06-23 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0029_auto_20190622_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaraccount',
            name='collar_account_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='collarindividual',
            name='collar_individual_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
