# Generated by Django 2.1.7 on 2019-06-23 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0030_auto_20190623_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaraccount',
            name='collar_account_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='collarindividual',
            name='collar_individual_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
