# Generated by Django 2.1.7 on 2019-07-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0031_auto_20190623_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaraccount',
            name='savannah_tracking_record_indexes',
            field=models.TextField(null=True),
        ),
    ]
