# Generated by Django 2.1.7 on 2019-07-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collars', '0032_collaraccount_savannah_tracking_record_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaraccount',
            name='account_ptr',
        ),
        migrations.RemoveField(
            model_name='collaraccount',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='collaraccount',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='collarindividual',
            name='collar_account',
        ),
        migrations.RemoveField(
            model_name='collarindividual',
            name='individual_ptr',
        ),
        migrations.DeleteModel(
            name='CollarProvider',
        ),
        migrations.RemoveField(
            model_name='orbcommcollarposition',
            name='position_ptr',
        ),
        migrations.RemoveField(
            model_name='savannahtrackingcollarposition',
            name='position_ptr',
        ),
        migrations.DeleteModel(
            name='CollarAccount',
        ),
        migrations.DeleteModel(
            name='CollarIndividual',
        ),
        migrations.DeleteModel(
            name='OrbcommCollarPosition',
        ),
        migrations.DeleteModel(
            name='SavannahTrackingCollarPosition',
        ),
    ]
