# Generated by Django 2.1.7 on 2019-04-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20190420_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityalert',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityalert',
            name='level',
            field=models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('severe', 'severe')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityalert',
            name='message',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitychange',
            name='message',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
