# Generated by Django 2.1.7 on 2019-04-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20190420_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityalert',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterModelOptions(
            name='activitychange',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.RenameField(
            model_name='activityalert',
            old_name='is_hidden',
            new_name='is_ignored',
        ),
    ]
