# Generated by Django 2.1.7 on 2019-04-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20190420_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityalert',
            name='is_ignored',
        ),
        migrations.AddField(
            model_name='activityalert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activitychange',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
