# Generated by Django 2.1.7 on 2019-05-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20190420_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityalert',
            name='datetime_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activityalert',
            name='datetime_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
