# Generated by Django 2.1.7 on 2019-09-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='write_key',
            field=models.CharField(max_length=100),
        ),
    ]
