# Generated by Django 2.1.7 on 2019-09-24 19:15

import caracal.common.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_source', '0002_auto_20190924_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('datetime_recorded', models.DateTimeField(null=True)),
                ('temperature_celcius', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('altitude_m', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('speed_kmh', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.AlterField(
            model_name='source',
            name='datetime_created',
            field=models.DateTimeField(default=caracal.common.models.get_utc_datetime_now),
        ),
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_source.Source'),
        ),
    ]
