# Generated by Django 2.1.7 on 2019-09-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_source', '0003_auto_20190924_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='altitude_m',
            new_name='alt_m',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='temperature_celcius',
            new_name='temp_c',
        ),
    ]
