# Generated by Django 2.1.7 on 2019-09-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_source', '0004_auto_20190924_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
