# Generated by Django 2.1.7 on 2019-09-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_source', '0005_record_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='temp_c',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
