# Generated by Django 2.1.7 on 2019-10-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_source', '0006_auto_20190926_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cloudwatch_get_data_rule_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='cloudwatch_update_kml_rule_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
