# Generated by Django 2.1.7 on 2020-11-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_source', '0009_auto_20191016_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='custom_source.Device'),
        ),
    ]
