# Generated by Django 2.1.7 on 2019-09-06 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0022_account_is_demo'),
        ('drives', '0009_auto_20190828_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('drive_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drives.DriveFileAccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('agol', 'agol'), ('google_earth', 'google_earth')], max_length=50)),
                ('status', models.CharField(choices=[('connected', 'connected'), ('disconnected', 'disconnected'), ('pending', 'pending')], default='pending', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealtimeAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('emails', models.TextField(blank=True, null=True)),
                ('phone_numbers', models.TextField(blank=True, null=True)),
                ('max_daily_distance_km', models.IntegerField(null=True)),
                ('max_weekly_distance_km', models.IntegerField(null=True)),
                ('immobility_wait_min', models.IntegerField(null=True)),
                ('immobility_distance_m', models.IntegerField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Organization')),
                ('realtime_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.RealTimeAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outputs.DataOutput'),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='realtime_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.RealTimeAccount'),
        ),
    ]
