# Generated by Django 2.1.7 on 2019-09-12 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='realtime_alert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outputs.RealtimeAlert'),
        ),
        migrations.AlterField(
            model_name='dataoutput',
            name='type',
            field=models.CharField(choices=[('agol', 'agol'), ('database', 'database'), ('google_earth', 'google_earth')], max_length=50),
        ),
    ]
