# Generated by Django 2.1.7 on 2019-09-12 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0002_auto_20190912_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='drive_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='drives.DriveFileAccount'),
        ),
        migrations.AlterField(
            model_name='dataconnection',
            name='realtime_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='account.RealTimeAccount'),
        ),
        migrations.AlterField(
            model_name='dataconnection',
            name='realtime_alert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='outputs.RealtimeAlert'),
        ),
    ]
