# Generated by Django 2.1.7 on 2019-09-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0003_auto_20190912_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataoutput',
            name='type',
            field=models.CharField(choices=[('output_agol', 'output_agol'), ('output_database', 'output_database'), ('output_kml', 'output_kml')], max_length=50),
        ),
    ]
