# Generated by Django 2.1.7 on 2019-09-24 19:15

import caracal.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0004_auto_20190913_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='datetime_created',
            field=models.DateTimeField(default=caracal.common.models.get_utc_datetime_now),
        ),
        migrations.AlterField(
            model_name='dataoutput',
            name='datetime_created',
            field=models.DateTimeField(default=caracal.common.models.get_utc_datetime_now),
        ),
        migrations.AlterField(
            model_name='realtimealert',
            name='datetime_created',
            field=models.DateTimeField(default=caracal.common.models.get_utc_datetime_now),
        ),
    ]
