# Generated by Django 2.1.7 on 2019-09-27 18:01

import caracal.common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20190927_1801'),
        ('custom_source', '0006_auto_20190926_1923'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outputs', '0005_auto_20190924_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgolAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_created', models.DateTimeField(default=caracal.common.models.get_utc_datetime_now)),
                ('datetime_updated', models.DateTimeField(null=True)),
                ('datetime_deleted', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('oauth_access_token', models.TextField(blank=True, null=True)),
                ('oauth_access_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('oauth_refresh_token', models.TextField(blank=True, null=True)),
                ('group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_service_url', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agol_account', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agol_accounts', to='account.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dataoutput',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='output',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='realtime_alert',
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='custom_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='custom_source.Source'),
        ),
        migrations.AlterField(
            model_name='dataconnection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='account.Organization'),
        ),
        migrations.DeleteModel(
            name='DataOutput',
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='agol_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='outputs.AgolAccount'),
        ),
    ]
