# Generated by Django 2.1.7 on 2019-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0006_auto_20190927_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='cloudwatch_update_rule_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
