# Generated by Django 2.1.7 on 2019-10-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0007_dataconnection_cloudwatch_update_rule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='agol_layer_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='agol_record_index',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
