# Generated by Django 2.1.7 on 2019-10-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0008_auto_20191006_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='agol_sheet_ids_to_layer_ids',
            field=models.TextField(null=True),
        ),
    ]
