# Generated by Django 2.1.7 on 2019-11-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0009_dataconnection_agol_sheet_ids_to_layer_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='agol_individual_layer_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
