# Generated by Django 2.1.7 on 2019-11-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0010_dataconnection_agol_individual_layer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='cloudwatch_update_individual_rule_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
