# Generated by Django 2.1.7 on 2019-11-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0011_dataconnection_cloudwatch_update_individual_rule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agolaccount',
            name='feature_service_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
