# Generated by Django 2.1.7 on 2020-01-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jackal', '0005_auto_20191024_1006'),
        ('outputs', '0012_agolaccount_feature_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='jackal_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='jackal.Network'),
        ),
    ]
