# Generated by Django 2.1.7 on 2020-02-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0013_dataconnection_jackal_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='jackal_calls_record_index',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='jackal_contacts_record_index',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='jackal_texts_record_index',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='jackal_wa_calls_record_index',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='jackal_wa_groups_record_index',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='jackal_wa_messages_record_index',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='jackal_wa_users_record_index',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
