# Generated by Django 2.1.7 on 2020-02-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0014_auto_20200218_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataconnection',
            name='jackal_calls_record_index',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='jackal_contacts_record_index',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='jackal_texts_record_index',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='jackal_wa_calls_record_index',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='jackal_wa_groups_record_index',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='jackal_wa_messages_record_index',
        ),
        migrations.RemoveField(
            model_name='dataconnection',
            name='jackal_wa_users_record_index',
        ),
    ]
