# Generated by Django 2.1.7 on 2020-02-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0015_auto_20200219_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='JackalAgolConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jackal_calls_layer_id', models.CharField(max_length=100, null=True)),
                ('jackal_calls_record_index', models.IntegerField(default=-1, null=True)),
                ('jackal_contacts_layer_id', models.CharField(max_length=100, null=True)),
                ('jackal_contacts_record_index', models.IntegerField(default=-1, null=True)),
                ('jackal_texts_layer_id', models.CharField(max_length=100, null=True)),
                ('jackal_texts_record_index', models.IntegerField(default=-1, null=True)),
                ('jackal_wa_calls_layer_id', models.CharField(max_length=100, null=True)),
                ('jackal_wa_calls_record_index', models.IntegerField(default=-1, null=True)),
                ('jackal_wa_groups_layer_id', models.CharField(max_length=100, null=True)),
                ('jackal_wa_groups_record_index', models.IntegerField(default=-1, null=True)),
                ('jackal_wa_messages_layer_id', models.CharField(max_length=100, null=True)),
                ('jackal_wa_messages_record_index', models.IntegerField(default=-1, null=True)),
                ('jackal_wa_users_layer_id', models.CharField(max_length=100, null=True)),
                ('jackal_wa_users_record_index', models.IntegerField(default=-1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='jackal_connection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='outputs.JackalAgolConnection'),
        ),
    ]
