# Generated by Django 2.1.7 on 2020-02-19 09:20

import caracal.common.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0016_auto_20200219_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackalagolconnection',
            name='datetime_created',
            field=models.DateTimeField(default=caracal.common.models.get_utc_datetime_now),
        ),
        migrations.AddField(
            model_name='jackalagolconnection',
            name='datetime_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jackalagolconnection',
            name='datetime_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jackalagolconnection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jackalagolconnection',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
