# Generated by Django 2.1.7 on 2020-02-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0017_auto_20200219_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataconnection',
            old_name='jackal_connection',
            new_name='jackal_agol_connection',
        ),
    ]
