# Generated by Django 2.1.7 on 2020-02-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0018_auto_20200219_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jackalagolconnection',
            old_name='jackal_calls_layer_id',
            new_name='jackal_calls_table_id',
        ),
        migrations.RenameField(
            model_name='jackalagolconnection',
            old_name='jackal_contacts_layer_id',
            new_name='jackal_contacts_table_id',
        ),
        migrations.RenameField(
            model_name='jackalagolconnection',
            old_name='jackal_texts_layer_id',
            new_name='jackal_texts_table_id',
        ),
        migrations.RenameField(
            model_name='jackalagolconnection',
            old_name='jackal_wa_calls_layer_id',
            new_name='jackal_wa_calls_table_id',
        ),
        migrations.RenameField(
            model_name='jackalagolconnection',
            old_name='jackal_wa_groups_layer_id',
            new_name='jackal_wa_groups_table_id',
        ),
        migrations.RenameField(
            model_name='jackalagolconnection',
            old_name='jackal_wa_messages_layer_id',
            new_name='jackal_wa_messages_table_id',
        ),
        migrations.RenameField(
            model_name='jackalagolconnection',
            old_name='jackal_wa_users_layer_id',
            new_name='jackal_wa_users_table_id',
        ),
    ]
